### ISSUE TITLE
400 Bad Request while installing tfsec

### ISSUE THREAD

**Issue by shirishp** [tfsec/tfsec-pr-commenter-action#8]
Partial `.github/workflows/tfsec.yaml` file contents
```yaml
name: tfsec

on: [push, pull_request]

jobs:
  tfsec:
    name: Terraform Security Scan and PR Commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Pull Request Commenter
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

The Github action fails intermittently with following log:

```
Build container for action use: '/home/runner/work/_actions/tfsec/tfsec-pr-commenter-action/main/Dockerfile'.
  /usr/bin/docker build -t 8a33c1:b550b8a0a509483d98f061f4371b7545 -f "/home/runner/work/_actions/tfsec/tfsec-pr-commenter-action/main/Dockerfile" "/home/runner/work/_actions/tfsec/tfsec-pr-commenter-action/main"
  Sending build context to Docker daemon  2.292MB
  
  Step 1/6 : FROM alpine:3.12
   ---> 13621d1b12d4
  Step 2/6 : RUN apk --no-cache --update add bash git     && rm -rf /var/cache/apk/*
   ---> Running in ad0873bae2ba
  fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
  fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
  (1/10) Installing ncurses-terminfo-base (6.2_p20200523-r0)
  (2/10) Installing ncurses-libs (6.2_p20200523-r0)
  (3/10) Installing readline (8.0.4-r0)
  (4/10) Installing bash (5.0.17-r0)
  Executing bash-5.0.17-r0.post-install
  (5/10) Installing ca-certificates (20191127-r4)
  (6/10) Installing nghttp2-libs (1.41.0-r0)
  (7/10) Installing libcurl (7.77.0-r0)
  (8/10) Installing expat (2.2.9-r1)
  (9/10) Installing pcre2 (10.35-r0)
  (10/10) Installing git (2.26.3-r0)
  Executing busybox-1.31.1-r20.trigger
  Executing ca-certificates-20191127-r4.trigger
  OK: 24 MiB in 24 packages
  Removing intermediate container ad0873bae2ba
   ---> 9c9a4e675717
  Step 3/6 : RUN wget -O - -q "$(wget -q https://api.github.com/repos/tfsec/tfsec/releases/latest -O - | grep -o -E "https://.+?tfsec-linux-amd64")" > tfsec     && install tfsec /usr/local/bin/
   ---> Running in 81c221f9a015
  wget: server returned error: HTTP/1.1 400 Bad Request
  The command '/bin/sh -c wget -O - -q "$(wget -q https://api.github.com/repos/tfsec/tfsec/releases/latest -O - | grep -o -E "https://.+?tfsec-linux-amd64")" > tfsec     && install tfsec /usr/local/bin/' returned a non-zero code: 1
  
  Warning: Docker build failed with exit code 1, back off 3.727 seconds before retry.
```

I am not sure how to debug the issue.
