### ISSUE TITLE
 SARIF URI scheme "git" did not match the checkout URI scheme "file"

### ISSUE THREAD

**Issue by apentsak-vitech** [tfsec/tfsec-pr-commenter-action#96]
Receive error: 
```
Waiting for processing to finish
  Analysis upload status is pending.
  Analysis upload status is failed.
Error: Code Scanning could not process the submitted SARIF file:
SARIF URI scheme "git" did not match the checkout URI scheme "file"
ConfigurationError: Code Scanning could not process the submitted SARIF file:
SARIF URI scheme "git" did not match the checkout URI scheme "file"
    at run (/home/runner/work/_actions/github/codeql-action/v3/lib/upload-sarif-action.js:65:15)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v3/lib/upload-sarif-action.js:76:9)
```

I've used this GitHub Action:
```
    - name: tfsec
      continue-on-error: true
      uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
      with:
        tfsec_formats: 'default,sarif'
        tfsec_args: '--force-all-dirs'
        working_directory: '${{ inputs.scan_dir }}'
        github_token: ${{ github.token }}
```

module sources as Terraform Registry in my terraform (Failed):

```
module "router_lambda" {
  source  = "terraform-aws-modules/lambda/aws"
  version = "7.2.1"
```

as a workaround changed to module sources as GitHub (Passed):
```
module "router_lambda" {
  source = "github.com/terraform-aws-modules/terraform-aws-lambda//modules/tags?ref=v7.2.1"
```
